name: yookassa_payments_flutter
description: Flutter plugin for YooKassa Payments.
version: 0.0.1
homepage: https://github.com/Rest00rer/yookassa-android-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.yoomoney.sdk.kassa.payments.flutter
        pluginClass: YookassaPaymentsFlutterPlugin
      ios:
        pluginClass: YookassaPaymentsFlutterPlugin
